name: CI

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: blog
  RUN_REGION: europe-west1

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn lint
      - run: yarn build

      - name: Login to docker.io
        uses: docker/login@v1
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: yarn make
      - run: yarn push

  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # Print gcloud info
      - name: Info
        run: gcloud info

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy blog \
            --quiet \
            --region "$RUN_REGION" \
            --image "docker.io/huangjien/website:latest" \
            --platform "managed" \
            --port 80 \
            --allow-unauthenticated
